language: php

php:
    - 5.5
    - 5.6

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

install:
   - composer require codeclimate/php-test-reporter

script: phpunit --coverage-clover build/logs/clover.xml
script: CODECLIMATE_REPO_TOKEN=f99bfc2e4433450c19864ef3d484bc7d608e3a0062733d5b2a0236f1cc0144a7 ./vendor/bin/test-reporter
